# SPDX-FileCopyrightText: 2022 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-2.0-only

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
