# SPDX-FileCopyrightText: 2020 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-2.0-only

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Packages.props', '**/global.json') }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        # Not strictly required, but codecov upload fails often. Maybe this helps...
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Build (Installer)
      run: msbuild Installer
    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v2
      with:
        name: msi-installer
        path: "Installer/bin/release/*.msi"
